INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Giorgio', 'Bruzzone', 'email1@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Emanuele', 'Cappanera', 'email2@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Andrea', 'Alivigni', 'email3@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Greta', 'Di Fabio', 'email4@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Alessandro', 'De Giacobbi', 'email5@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Gianluca', 'Ciceri', 'email6@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Tiziano', 'Gessa', 'email7@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Simone', 'Rizzo', 'email8@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Cristofer', 'Thompson', 'email9@gmail.com');
INSERT INTO compagni (NOME, COGNOME, EMAIL) VALUES ('Davide', 'Rivolta', 'email10@gmail.com');